databases:
  - name: spa_DB
    databaseName: spa_db
    user: spaApp
    region: singapore

services:
  - type: web
    name: spaApp
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: spaApp_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

